# Generated by Django 4.0.3 on 2023-03-20 22:52

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=100)),
                ('primer_nombre', models.CharField(max_length=250)),
                ('segundo_nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('femenino', 'femenino')], default='Masculino', max_length=50)),
                ('dob', models.DateField(verbose_name=builtins.max)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('departamento', models.TextField(blank=True, null=True)),
                ('posicion', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
