# Generated by Django 4.0.3 on 2023-03-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='genero',
            field=models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], default='masculino', max_length=50),
        ),
    ]
